
name: Test secrets

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Test secrets
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Test Node key.js
      run: node key.js   

    - name: Test Node secret
      run: |
        if [ "$KEY" == "9102a56a9ee365b235fd29563dd52b0a" ] 
        then 
          echo "Got NODE secret"
        else
          echo "Error getting NODE secret"  
        fi
      env: 
        KEY: ${{ secrets.KEY  }}     

    - name: Test Python secret
      run: |
        if [ "$KEY" == "9102a56a9ee365b235fd29563dd52b0a" ] 
        then 
          echo "Got PYTHON secret"
        else
          echo "Error getting PYTHON secret"  
        fi
      env: 
        KEY: ${{ secrets.KEY  }}             