name: Update Algolia with secret
on:
  push:
    branches:
      - main
jobs:
  update-algolia:
    name: Check for projects.csv updates and add records to Algolia
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Test Node Secret
      run: node key.js
   
    - name: Install dependencies
      run: python -m pip install --upgrade pip algoliasearch jproperties

    - name: Run algolia.py
      run: python algolia.py
      env:
        KEY: ${{ secrets.PYTHON_ALGOLIA_KEY }}
      
